### Python libraries for DataScience
#### DataScience:
    - ds is the field of study that combines programming skills,knowledge of 
        mathematic and statistics and  domain knowledge...
    - there are nearly 20 python libaries for data science
    - Top five python libraries are
        - numpy
        - pandas
        - matplot lib
        - tensorflow
        - scipy

#### numpy
    - it is n-dimensional array package,is python library and a fundamental package for
        scientific computing
    - it is used to create multidimensional arrays for fast operations

In [1]:
import numpy as np 
np.__version__


'1.16.2'

In [2]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

In [4]:
type(np.array([1,3,5,7]))

numpy.ndarray

In [6]:
#### create 1-d array
a=np.array([6,7,8,9])
print(a)
type(a)

[6 7 8 9]


numpy.ndarray

In [10]:
## 2-d array craetion
a=np.array([[6,7,8,9],[6,5,4,3]])
print(a)


[[6 7 8 9]
 [6 5 4 3]]


In [8]:
np.array((4,5,6,7))

array([4, 5, 6, 7])

### nd array attributes:
    - ndarray.ndim:it returns no of dimensions of aaray
    - ndarray.shape:length of the array of the array in tuple
    - ndarray.size:size of the array
    - ndarray.dtype:whether the given data is which type
    - ndarray.itemsize:returns the size in bytes of each element in array

In [16]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a.size)
print(a.itemsize)

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
int32
8
4


In [18]:
a=np.array([10,40,5.6,8.9])
a.dtype

dtype('float64')

In [19]:
a=np.array(['srikanya','siri'])
a.dtype

dtype('<U8')

In [20]:
print(help(np.array))

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}

### arange(array range)

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
print(np.arange(11,21))
print(np.arange(10,100,2))
print(np.arange(10,4,-2))
print(np.arange(10,4,-1))
print(np.arange(3,5,0.1))
print(np.arange(2.5,10,0.75))

[11 12 13 14 15 16 17 18 19 20]
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]
[10  8  6]
[10  9  8  7  6  5]
[3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7
 4.8 4.9]
[2.5  3.25 4.   4.75 5.5  6.25 7.   7.75 8.5  9.25]


### linspace
    (st,end,no of partitions)

In [31]:
print(np.linspace(1,10,10))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [32]:
print(np.linspace(1,10,5))

[ 1.    3.25  5.5   7.75 10.  ]


#### array initialization
    - ones()
    - zeros()
    - full()
    - eye()
    - diag()

In [34]:
np.ones((3,2,4))  # 1- no of matrices

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [36]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [37]:
np.full((2,3,4),7)

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [38]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
a=np.array(['siri','giri','vani'])
np.diag(a)

array([['siri', '', ''],
       ['', 'giri', ''],
       ['', '', 'vani']], dtype='<U4')

In [40]:
np.diag([3,4,5,6])

array([[3, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6]])

### random

In [43]:
print(np.random.randint(1,10,4))

[7 3 1 3]


In [45]:
print(np.random.randint(10,100,(3,2)))

[[32 20]
 [40 33]
 [53 88]]


In [46]:
print(np.random.rand(3,2))

[[0.39953707 0.82306942]
 [0.11081372 0.87381401]
 [0.33436205 0.04708424]]


In [47]:
print(np.random.random((3,5)))

[[0.14701008 0.02708693 0.83139298 0.22055682 0.21655449]
 [0.4027849  0.97352222 0.02114127 0.12609425 0.96768395]
 [0.0684373  0.18543202 0.17048331 0.0618117  0.88035486]]


In [49]:
print(np.random.normal())

1.391410418556995


## index slicing

In [51]:
a=np.arange(100)

In [52]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [53]:
a[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [54]:
a[1:20:2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [55]:
a[20:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
       88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [56]:
a2=np.arange(25).reshape(5,5)
print(a2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [57]:
a2[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [58]:
a2[1:3,3:5]

array([[ 8,  9],
       [13, 14]])

In [59]:
a2[1:5:2,1:5:2]

array([[ 6,  8],
       [16, 18]])

In [ ]:
### stacking
        - hstack 
        - vstack

In [62]:
x1=np.random.randint(1,10,(2,2))
x2=np.random.randint(1,10,(2))
print(x1)
print(x2)
np.vstack((x1,x2))

[[3 1]
 [7 2]]
[3 4]


array([[3, 1],
       [7, 2],
       [3, 4]])

In [64]:
x3=np.random.randint(1,10,(2,1))
print(x3)
np.hstack((x1,x3))

[[7]
 [2]]


array([[3, 1, 7],
       [7, 2, 2]])

#### mathematical methods

In [65]:
a1=np.arange(10)

In [66]:
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [67]:
np.sum(a1)

45

In [68]:
np.mean(a1)

4.5

In [69]:
np.median(a1)

4.5

In [70]:
np.std(a1)

2.8722813232690143

In [71]:
np.log(5)

1.6094379124341003

In [72]:
np.log([3,4,5])

array([1.09861229, 1.38629436, 1.60943791])

In [73]:
np.exp(1)

2.718281828459045

In [74]:
np.log(np.exp(1))

1.0